# Generated by Django 2.0.2 on 2018-02-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Item', 'item', 'name')
    ]
