# Generated by Django 2.0.2 on 2018-02-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180218_0102'),
        ('users', '0002_auto_20180218_0103'),
        ('polls', '0002_auto_20180218_0208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('student', 'item')},
        ),
    ]
