# Generated by Django 2.0.2 on 2018-02-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180218_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
