# Generated by Django 2.0.2 on 2018-02-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Student', 'student', 'name')
    ]
